#!/usr/bin/env python3
"""Writes the widget extensions' localized strings for every app locale, for
both iOS (Localizable.strings) and Android (strings.xml).

Model names the widget shares with the app (assets, units, karats, ranges,
"Portfolio") come straight from lib/l10n/app_<lang>.arb, keyed by their ARB
name, so the widget never drifts from the app's wording. Widget-only
phrases live in tool/widget_strings.json, keyed by their English text.

iOS keys a .strings entry by that ARB name (or the literal English text for
a widget-only phrase — see Style.swift's `L10n.key` / `L10n.text`). Android
resource names can't hold spaces or punctuation the way an iOS key can, so
each entry also gets a deterministic camelCase slug for its Android name
(ARB names are already valid identifiers and are reused as-is).

Run from the repo root after changing either source:
    python3 tool/generate_widget_strings.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALES = ["en", "ar", "es", "fr"]
SHARED = re.compile(r"^(asset[A-Z]\w*|unit[A-Z]\w*|karatShort\d+|range\w+|portfolioTitle)$")

ANDROID_RES_DIR = {"en": "values", "ar": "values-ar", "es": "values-es", "fr": "values-fr"}


def escape_strings(text: str) -> str:
    """Escaping for an iOS/macOS .strings value."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def escape_xml(text: str) -> str:
    """Escaping for an Android strings.xml value: XML entities, plus the
    apostrophe (Android's resource compiler treats an unescaped one as a
    verbatim-string marker)."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "\\'")
    )


def android_format(text: str) -> str:
    """iOS format specifiers ("%@") to Android's positional ones
    ("%1$s", "%2$s", ...), in order of appearance."""
    counter = iter(range(1, 10))
    return re.sub(r"%@", lambda _: f"%{next(counter)}$s", text)


def slugify(english: str) -> str:
    """A deterministic camelCase name for a widget-only string, derived from
    its English text (e.g. "Chart range" -> "widgetChartRange"). Prefixed so
    it can never collide with an ARB-derived name."""
    words = re.findall(r"[A-Za-z0-9]+", english)
    camel = words[0].lower() + "".join(w.capitalize() for w in words[1:])
    return f"widget{camel[0].upper()}{camel[1:]}"


def karat_key(karat: int) -> str:
    """Android-safe name for a karat picker option; iOS uses "24K" etc.
    directly since a .strings key can be any string."""
    return f"widgetKarat{karat}Short"


def build_entries(locale: str, arb: dict, widget_only: dict) -> dict[str, tuple[str, str]]:
    """Maps a stable Android resource name to (iOS key, localized text) for
    every string the widgets need in [locale]."""
    entries: dict[str, tuple[str, str]] = {
        name: (name, value)
        for name, value in arb.items()
        if SHARED.match(name) and isinstance(value, str) and "{" not in value
    }
    # The karat picker's options ("21K") read the same as the app's labels.
    for karat in (24, 22, 21, 18):
        entries[karat_key(karat)] = (f"{karat}K", arb[f"karatShort{karat}"])
    for english, translations in widget_only.items():
        value = english if locale == "en" else translations[locale]
        entries[slugify(english)] = (english, value)
    return entries


def write_ios(locale: str, entries: dict[str, tuple[str, str]]) -> None:
    out = ROOT / f"ios/QimaWidget/{locale}.lproj/Localizable.strings"
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = ["/* Generated by tool/generate_widget_strings.py. Do not edit. */", ""]
    pairs = {ios_key: value for ios_key, value in entries.values()}
    lines += [f'"{escape_strings(k)}" = "{escape_strings(v)}";' for k, v in sorted(pairs.items())]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{out.relative_to(ROOT)}: {len(pairs)} strings")


def write_android(locale: str, entries: dict[str, tuple[str, str]]) -> None:
    out = ROOT / f"android/app/src/main/res/{ANDROID_RES_DIR[locale]}/widget_generated_strings.xml"
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by tool/generate_widget_strings.py. Do not edit. -->",
        "<resources>",
    ]
    for name in sorted(entries):
        _, value = entries[name]
        lines.append(f'    <string name="{name}">{escape_xml(android_format(value))}</string>')
    lines.append("</resources>")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{out.relative_to(ROOT)}: {len(entries)} strings")


def main() -> None:
    widget_only = json.loads((ROOT / "tool/widget_strings.json").read_text(encoding="utf-8"))
    for locale in LOCALES:
        arb = json.loads((ROOT / f"lib/l10n/app_{locale}.arb").read_text(encoding="utf-8"))
        entries = build_entries(locale, arb, widget_only)
        write_ios(locale, entries)
        write_android(locale, entries)


if __name__ == "__main__":
    main()
