#!/usr/bin/env python3
"""Writes the iOS widget extension's Localizable.strings for every app locale.

Model names the widget shares with the app (assets, units, karats, ranges,
"Portfolio") come straight from lib/l10n/app_<lang>.arb, keyed by their ARB
name, so the widget never drifts from the app's wording. Widget-only
phrases live in tool/widget_strings.json, keyed by their English text.

Run from the repo root after changing either source:
    python3 tool/generate_widget_strings.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALES = ["en", "ar", "es", "fr"]
SHARED = re.compile(r"^(asset[A-Z]\w*|unit[A-Z]\w*|karatShort\d+|range\w+|portfolioTitle)$")


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main() -> None:
    widget_only = json.loads((ROOT / "tool/widget_strings.json").read_text(encoding="utf-8"))
    for locale in LOCALES:
        arb = json.loads((ROOT / f"lib/l10n/app_{locale}.arb").read_text(encoding="utf-8"))
        entries = {k: v for k, v in arb.items() if SHARED.match(k) and isinstance(v, str) and "{" not in v}
        # The karat picker's options ("21K") read the same as the app's labels.
        for karat in (24, 22, 21, 18):
            entries[f"{karat}K"] = arb[f"karatShort{karat}"]
        for english, translations in widget_only.items():
            entries[english] = english if locale == "en" else translations[locale]

        out = ROOT / f"ios/QimaWidget/{locale}.lproj/Localizable.strings"
        out.parent.mkdir(parents=True, exist_ok=True)
        lines = ["/* Generated by tool/generate_widget_strings.py. Do not edit. */", ""]
        lines += [f'"{escape(k)}" = "{escape(v)}";' for k, v in sorted(entries.items())]
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"{out.relative_to(ROOT)}: {len(entries)} strings")


if __name__ == "__main__":
    main()
