// Regenerates lib/l10n/currency_names.dart from the CLDR currency display
// names bundled with Node's ICU (`Intl.DisplayNames`), for every locale the
// app ships. Run from the repo root: `node tool/generate_currency_names.mjs`.
import { readdirSync, writeFileSync } from 'node:fs';

const locales = readdirSync('lib/l10n')
  .map((f) => /^app_(\w+)\.arb$/.exec(f)?.[1])
  .filter(Boolean)
  .sort();
const codes = Intl.supportedValuesOf('currency');
const esc = (s) => s.replaceAll('\\', '\\\\').replaceAll("'", "\\'").replaceAll('$', '\\$');

let out = `// GENERATED by tool/generate_currency_names.mjs — do not edit by hand.
// CLDR currency display names (ICU ${process.versions.icu}, CLDR ${process.versions.cldr}).

/// Localized display name for an ISO 4217 [code], e.g. \`KWD\` →
/// "Kuwaiti Dinar" / "دينار كويتي". Falls back to English, then to [code].
String currencyDisplayName(String code, String languageCode) {
  return _names[languageCode]?[code] ?? _names['en']?[code] ?? code;
}

const Map<String, Map<String, String>> _names = {
`;
for (const locale of locales) {
  const names = new Intl.DisplayNames([locale], { type: 'currency', fallback: 'none' });
  out += `  '${locale}': {\n`;
  for (const code of codes) {
    const name = names.of(code);
    if (name && name !== code) out += `    '${code}': '${esc(name)}',\n`;
  }
  out += '  },\n';
}
out += '};\n';
writeFileSync('lib/l10n/currency_names.dart', out);
console.log(`${locales.join(', ')}: ${codes.length} currencies`);
